import { Inter } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from './context/ThemeContext'
import { CartProvider } from './context/CartContext'
import FacebookPixel from './utils/FacebookPixel'
import ScrollToTop from './components/ScrollToTop'
import ResponsiveNavbar from './components/ResponsiveNavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
      <ThemeProvider>
       <CartProvider>
        <ResponsiveNavbar/>
        {children}
        <FacebookPixel/>
       <ScrollToTop />
       </CartProvider>
     </ThemeProvider>
      </body>
    </html>
  )
}


{/* <>    
<ThemeProvider>
<CartProvider>
<Layout>
  <Component {...pageProps} />
  <FacebookPixel/>
  <ScrollToTop />
</Layout>
</CartProvider>
</ThemeProvider>
</> */}