name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        password: ${{ secrets.PASSWORD }}
        source: "."
        target: "/home/akinthe/next-level-funding2-dev"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        password: ${{ secrets.PASSWORD }}
        script: |
            cd ~
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            export PATH="$PATH:/home/akinthe/.nvm/versions/node/v18.18.2/bin/yarn:/home/akinthe/.nvm/versions/node/v18.18.2/bin/yarn"
            export PATH="$PATH:/home/akinthe/.nvm/versions/node/v18.18.2/bin/pm2:/home/akinthe/.nvm/versions/node/v18.18.2/bin/pm2"
            cd /home/akinthe/next-level-funding2-dev
            yarn install
            yarn run build
            pm2 stop all
            pm2 del all
            pm2 start "yarn run start" --name "next-level-funding-2.0"